name: searchable_appbar
version: 0.0.3
description: A customizable Flutter AppBar widget with built-in search functionality.
repository: https://github.com/NazrulIslam991/searchable_appbar
license: MIT


environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
